import { DailyState } from '../types';

export const INITIAL_DAILY_STATE: DailyState = {
  date: new Date().toISOString().split('T')[0],
  current: {
    location: 'Office',
    activity: 'Morning planning & review',
    energy: 'NORMAL',
    focusTaskId: 'task-3',
    updatedAt: '09:38',
  },
  fixedEvents: [
    {
      id: 'fix-1',
      time: '11:30',
      endTime: '12:30',
      title: 'Boss Meeting',
      category: 'OFFICE',
      location: 'Conference Room B',
      notes: 'Review Q3 workflow submission & team goals',
    },
    {
      id: 'fix-2',
      time: '16:00',
      endTime: '16:45',
      title: 'Client Strategy Call',
      category: 'CLIENT',
      location: 'Google Meet',
      notes: 'Review updated contract and onboarding milestones',
    },
  ],
  timeline: [
    {
      id: 'time-1',
      time: '07:30',
      type: 'EVENT',
      description: 'Woke up & morning routine',
      location: 'Home',
    },
    {
      id: 'time-2',
      time: '09:10',
      type: 'DEPARTURE',
      description: 'Reached office (10 min traffic delay)',
      location: 'Office',
      plannedTime: '09:00',
      varianceMinutes: 10,
    },
    {
      id: 'time-3',
      time: '09:38',
      type: 'UPDATE',
      description: 'Logged morning update & task alignment',
      location: 'Office',
    },
    {
      id: 'time-4',
      time: '09:40',
      type: 'TASK_COMPLETED',
      description: 'Morning content post published',
      relatedTaskId: 'task-1',
      location: 'Office',
    },
    {
      id: 'time-5',
      time: '12:30',
      type: 'TASK_COMPLETED',
      description: 'Final workflow submitted to management',
      relatedTaskId: 'task-2',
      location: 'Office',
    },
  ],
  tasks: [
    {
      id: 'task-1',
      title: 'Morning content post',
      category: 'CONTENT',
      owner: 'ME',
      status: 'DONE',
      priority: 8,
      createdAt: '07:30',
      completedAt: '09:40',
      recurring: true,
      recurrenceRule: 'DAILY',
      notes: 'Published daily insights post to LinkedIn/Twitter',
    },
    {
      id: 'task-2',
      title: 'Prepare and submit final workflow',
      category: 'OFFICE',
      owner: 'ME',
      status: 'DONE',
      priority: 9,
      createdAt: '09:15',
      completedAt: '12:30',
      notes: 'Handed off to IT for CRM implementation',
    },
    {
      id: 'task-3',
      title: 'Job/recruiter correspondence & follow-ups',
      category: 'CAREER',
      owner: 'ME',
      status: 'ACTIVE',
      priority: 9,
      createdAt: '09:38',
      estimatedMinutes: 45,
      location: 'OFFICE',
      context: 'COMPUTER',
      notes: 'Review pending applications and schedule screening calls before lunch',
    },
    {
      id: 'task-4',
      title: 'Client work proposal revision',
      category: 'CLIENT',
      owner: 'ME',
      status: 'NEXT',
      priority: 8,
      createdAt: '09:38',
      estimatedMinutes: 40,
      location: 'OFFICE',
      context: 'COMPUTER',
      notes: 'Update fee structure for enterprise proposal',
    },
    {
      id: 'task-5',
      title: 'Implement workflow in CRM',
      category: 'OFFICE',
      owner: 'IT_TEAM',
      status: 'WAITING',
      priority: 7,
      createdAt: '12:30',
      notes: 'Waiting for IT team implementation (~24 hours estimate)',
    },
    {
      id: 'task-6',
      title: 'Test CRM workflow',
      category: 'OFFICE',
      owner: 'ME',
      status: 'BLOCKED',
      priority: 8,
      createdAt: '12:30',
      estimatedMinutes: 30,
      blockedBy: 'Implement workflow in CRM (IT_TEAM)',
      trigger: 'IT confirms CRM workflow is live',
      notes: 'Verify pipeline stages, permissions, and email automation triggers',
    },
    {
      id: 'task-7',
      title: 'Next content reel script drafting',
      category: 'CONTENT',
      owner: 'ME',
      status: 'NEXT',
      priority: 6,
      createdAt: '09:45',
      estimatedMinutes: 30,
      context: 'PHONE',
    },
    {
      id: 'task-8',
      title: 'Bring water bottle from home at lunch',
      category: 'PERSONAL',
      owner: 'ME',
      status: 'DONE',
      priority: 5,
      createdAt: '09:38',
      completedAt: '13:45',
    },
    {
      id: 'task-9',
      title: 'Khabarzaar weekly digest topics curation',
      category: 'KHABARZAAR',
      owner: 'ME',
      status: 'CAPTURED',
      priority: 5,
      createdAt: '10:15',
      estimatedMinutes: 25,
      notes: 'Captured idea during morning review without breaking focus',
    },
  ],
  reminders: [
    {
      id: 'rem-1',
      type: 'TIME_BASED',
      triggerCondition: '13:00',
      message: 'Grab water bottle when going home for lunch',
      isDone: true,
      createdAt: '09:38',
    },
    {
      id: 'rem-2',
      type: 'EVENT_TRIGGERED',
      triggerCondition: 'When IT confirms CRM workflow is ready',
      message: 'Run full verification tests on CRM automation flow',
      isDone: false,
      createdAt: '12:30',
      relatedTaskId: 'task-6',
    },
    {
      id: 'rem-3',
      type: 'LOCATION_BASED',
      triggerCondition: 'Arriving home this evening',
      message: 'Take laptop charger and notebook',
      isDone: false,
      createdAt: '10:00',
    },
  ],
  timetable: [
    {
      id: 'slot-1',
      title: 'Morning Fuel & Breakfast',
      category: 'HEALTH',
      startTime: '07:30',
      endTime: '08:15',
      durationMinutes: 45,
      days: 'DAILY',
      status: 'COMPLETED',
      location: 'HOME',
      isRegularHabit: true,
      targetMetric: 'Hydration + High-protein breakfast',
      iconKey: 'breakfast',
      notes: 'Fuel up before workout and prepare for the day',
    },
    {
      id: 'slot-2',
      title: 'Gym & Physical Fitness',
      category: 'HEALTH',
      startTime: '08:15',
      endTime: '09:15',
      durationMinutes: 60,
      days: 'MON_WED_FRI',
      status: 'COMPLETED',
      location: 'GYM',
      isRegularHabit: true,
      targetMetric: 'Strength training + 15m stretch',
      iconKey: 'gym',
      notes: 'Maintain peak energy levels and mental focus',
    },
    {
      id: 'slot-3',
      title: 'Social Media & Content Posting',
      category: 'CONTENT',
      startTime: '09:40',
      endTime: '10:15',
      durationMinutes: 35,
      days: 'WEEKDAYS',
      status: 'COMPLETED',
      location: 'OFFICE',
      isRegularHabit: true,
      targetMetric: '1 LinkedIn/Twitter post + engage with 10 replies',
      iconKey: 'social',
      notes: 'Morning high-engagement window',
    },
    {
      id: 'slot-4',
      title: 'Core Office & Deep Work Block',
      category: 'OFFICE',
      startTime: '10:15',
      endTime: '13:00',
      durationMinutes: 165,
      days: 'WEEKDAYS',
      status: 'ACTIVE',
      location: 'OFFICE',
      isRegularHabit: true,
      targetMetric: 'High-leverage tasks & Boss sync at 11:30',
      iconKey: 'work',
      notes: 'Uninterrupted deep focus window',
    },
    {
      id: 'slot-5',
      title: 'Healthy Lunch Break & Walk',
      category: 'HEALTH',
      startTime: '13:00',
      endTime: '14:00',
      durationMinutes: 60,
      days: 'DAILY',
      status: 'PENDING',
      location: 'HOME',
      isRegularHabit: true,
      targetMetric: 'Nutritious lunch + 15 min walk',
      iconKey: 'lunch',
      notes: 'Step away from screen to recharge cognitive battery',
    },
    {
      id: 'slot-6',
      title: 'Client Work & Career Follow-ups',
      category: 'CAREER',
      startTime: '14:00',
      endTime: '16:30',
      durationMinutes: 150,
      days: 'WEEKDAYS',
      status: 'PENDING',
      location: 'OFFICE',
      isRegularHabit: true,
      targetMetric: 'Recruiter responses, proposals, delivery review',
      iconKey: 'work',
      notes: 'External collaboration and momentum',
    },
    {
      id: 'slot-7',
      title: 'Afternoon Tea & Energy Reset',
      category: 'PERSONAL',
      startTime: '16:30',
      endTime: '17:00',
      durationMinutes: 30,
      days: 'WEEKDAYS',
      status: 'PENDING',
      location: 'OFFICE',
      isRegularHabit: true,
      targetMetric: 'Green tea + posture stretches',
      iconKey: 'coffee',
      notes: 'Pre-evening reset to prevent afternoon slump',
    },
    {
      id: 'slot-8',
      title: 'Script Writing & Reel Production',
      category: 'CONTENT',
      startTime: '17:30',
      endTime: '18:30',
      durationMinutes: 60,
      days: 'WEEKDAYS',
      status: 'PENDING',
      location: 'HOME',
      isRegularHabit: true,
      targetMetric: 'Draft 1 full script or review Khabarzaar clips',
      iconKey: 'script',
      notes: 'Creative flow block',
    },
    {
      id: 'slot-9',
      title: 'Evening Review & Wind-down',
      category: 'PERSONAL',
      startTime: '21:30',
      endTime: '22:00',
      durationMinutes: 30,
      days: 'DAILY',
      status: 'PENDING',
      location: 'HOME',
      isRegularHabit: true,
      targetMetric: 'Log review, celebrate wins, set tomorrow anchors',
      iconKey: 'night',
      notes: 'Reflect and prepare for restful sleep',
    },
  ],
  nextBestAction: {
    taskId: 'task-3',
    title: 'Job/recruiter correspondence & follow-ups',
    rationale: 'High priority career momentum window (45 min) before upcoming 11:30 Boss meeting.',
    category: 'CAREER',
    estimatedMinutes: 45,
    urgencyReason: 'Available 1h 52m window before 11:30 Boss Meeting; avoids switching cost',
    secondaryRecommendations: [
      'Client work proposal revision (40 mins)',
      'Next content reel script drafting (30 mins)',
    ],
  },
  conversationHistory: [
    {
      id: 'msg-1',
      sender: 'user',
      text: 'I reached office at 9:10. Logging this at 9:38. Morning content post is already done. I have a boss meeting at 11:30.',
      timestamp: '09:38',
    },
    {
      id: 'msg-2',
      sender: 'ai',
      text: 'Logged arrival at office at 9:10 and marked Morning Content Post as DONE. Added Boss Meeting at 11:30 as planning anchor. You have an uninterrupted window until 11:30. Next best action: Focus on Job/recruiter correspondence.',
      timestamp: '09:38',
      changesSummary: {
        tasksDone: ['Morning content post'],
        timelineAdded: ['Reached office at 09:10', 'Morning content post published'],
        nextAction: 'Job/recruiter correspondence',
      },
    },
    {
      id: 'msg-3',
      sender: 'user',
      text: 'I submitted the final workflow. Sir will ask IT to implement it in CRM. Once IT finishes, I need to test it.',
      timestamp: '12:30',
    },
    {
      id: 'msg-4',
      sender: 'ai',
      text: 'The workflow is complete on your side. Marked "Prepare and submit final workflow" as DONE. Moved "Implement workflow in CRM" to WAITING (Owner: IT_TEAM). Created "Test CRM workflow" in BLOCKED status pending IT confirmation. Move to your next independent priority: Client work proposal.',
      timestamp: '12:30',
      changesSummary: {
        tasksDone: ['Prepare and submit final workflow'],
        tasksWaiting: ['Implement workflow in CRM (IT_TEAM)'],
        tasksBlocked: ['Test CRM workflow (Waiting for IT trigger)'],
        nextAction: 'Client work proposal revision',
      },
    },
  ],
};
